apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-devops-pipelines
    component: basket
  name: basket-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: auto-devops-pipelines
    component: basket
    type: webapi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-devops-pipelines
    component: catalog
  name: catalog-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: auto-devops-pipelines
    component: catalog
    type: webapi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-devops-pipelines
    component: identity
  name: identity-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: auto-devops-pipelines
    component: identity
    type: webapi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-devops-pipelines
    component: marketing
  name: marketing-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: auto-devops-pipelines
    component: marketing
    type: webapi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-devops-pipelines
    component: ordering
  name: ordering-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: auto-devops-pipelines
    component: ordering
    type: webapi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auto-devops-pipelines
    component: payment
  name: payment-api
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: auto-devops-pipelines
    component: payment
    type: webapi